resources:
  - url: http://127.0.0.1:5000/various-buttons-cardjs
    type: module
views:
  - cards:
      - type: custom:various-buttons-card
        name: Boilerplate Card Development
        entity: sun.sun
        test_gui: true
